name: Build caddy-custom

on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - caddy-custom/Dockerfile

env:
  DOCKER_BUILDKIT: 1
  DOCKER_NAME: caddy-custom

jobs:
  metadata:
    name: Get image and repository details
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}
      labels: ${{ steps.metadata.outputs.labels }}
      tags: ${{ steps.metadata.outputs.tags }}
      platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/arm/v7,linux/arm/v6
      description: ${{ steps.desc.outputs.description }}

    steps:
      - name: Checkout repository (sparse for Dockerfile only)
        uses: actions/checkout@v4
        with:
          ref: main
          sparse-checkout: |
            caddy-custom/Dockerfile

      - name: Parse Caddy version
        id: version
        run: |
          echo "version=$(grep -Eo 'caddy:[0-9]+\.[0-9]+\.[0-9]+$' $DOCKER_NAME/Dockerfile | cut -d ':' -f2)" | tee -a $GITHUB_OUTPUT

      - name: Extract Caddy modules from Dockerfile
        id: modules
        run: |
          MODULES=$(grep -oP '(?<=--with )[^\\]+' caddy-custom/Dockerfile | xargs | tr ' ' ', ')
          echo "modules=$MODULES" | tee -a $GITHUB_OUTPUT

      - name: Set dynamic Docker description
        id: desc
        run: |
          if [ -z "${{ steps.modules.outputs.modules }}" ]; then
            DESC="Caddy Docker custom build with no extra modules"
          else
            DESC="Caddy Docker custom build with modules: ${{ steps.modules.outputs.modules }}"
          fi
          echo "description=$DESC" | tee -a $GITHUB_OUTPUT
          echo "DOCKER_DESCRIPTION=$DESC" >> $GITHUB_ENV

      - name: Generate image metadata with Caddy version and modules
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_NAME }}
          tags: |
            type=semver,pattern={{version}},value=v${{ steps.version.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=v${{ steps.version.outputs.version }}
            type=semver,pattern={{major}},value=v${{ steps.version.outputs.version }}
          labels: |
            org.opencontainers.image.title=${{ env.DOCKER_NAME }}
            org.opencontainers.image.description=${{ env.DOCKER_DESCRIPTION }}

  build:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    needs: metadata

    steps:
      - name: Checkout repository (sparse for Dockerfile only)
        uses: actions/checkout@v4
        with:
          ref: main
          sparse-checkout: |
            caddy-custom/Dockerfile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # (Optional) Add Quay login here if you want to push to Quay as well

      - name: Build and publish container image (with cache)
        uses: docker/build-push-action@v6
        id: build
        with:
          context: .
          file: ./${{ env.DOCKER_NAME }}/Dockerfile
          push: true
          provenance: false
          tags: ${{ needs.metadata.outputs.tags }}
          labels: ${{ needs.metadata.outputs.labels }}
          platforms: ${{ needs.metadata.outputs.platforms }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
